version : "3.8"
services: 
  backend: 
    build: ./backend
    ports:
     - "3001:3001"
    container_name: node-backend
    restart : always

  frontend: 
    build: ./frontend
    ports:
     - "3000:3000"
    container_name: react-frontend
    restart : always
    